# @package _global_
defaults:
  - /hydra: default
  - /envs@env_train: empty
  - /rewards@env_train.reward: lines_shape
  - /envs@env_eval: empty
  - /rewards@env_eval.reward: lines_shape
  - /sb3_policies@policy: cnn1
  - /trains@_global_: ppo_eval
  - _self_

log_level: info                      # logging verbosity

run:
  name: cnn_ppo_run                  # run name (used for output dir)
  seed: 0                            # base RNG seed
  out_root: experiments              # output root directory
  tensorboard: true                  # enable TensorBoard logging
  device: cuda                       # cuda | cpu | auto
  n_envs: 64                         # number of parallel envs
  vec: dummy                       # subproc | dummy



