# @package _global_
defaults:
  - hydra: default
  - conf/envs@env_train: warmup
  - conf/rewards@env_train.reward: codemy_heuristic_delta
  - conf/envs@env_eval: empty
  - conf/rewards@env_eval.reward: codemy_heuristic_delta
  - conf/sb3_policies@policy: vit
  - conf/trains@_global_: ppo_eval
  - _self_

log_level: info

run:
  name: ppo_vit_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 12
  vec: subproc
  max_episode_steps: 500
