# @package _global_
defaults:
  - /hydra: default
  - /env_bundles: macro_discrete_warmup
  - _self_

# ------------------------------------------------------------------
# Dataset
# ------------------------------------------------------------------
dataset:
  name: codemy0_uniform_noise
  out_root: datasets/bc

  shards:
    shard_steps: 500_000
    num_shards: 1_000

  compression: true


# ------------------------------------------------------------------
# Run
# ------------------------------------------------------------------
run:
  seed: 123
  num_workers: 20
  progress_update_every_k: 10_000


# ------------------------------------------------------------------
# Generation
# ------------------------------------------------------------------
generation:
  episode_max_steps: 10_000

  noise:
    enabled: false
    interleave_prob: 0.0
    interleave_max_steps: 1


# ------------------------------------------------------------------
# Expert
# ------------------------------------------------------------------
expert:
  type: codemy0              # codemy0 | codemy1 | codemy2 | codemy2fast

  params: {}
    # codemy0 / codemy1 / codemy2 knobs
#    beam_from_depth: 0
#    beam_width: 10             # null -> use Rust defaults
#
#    codemy2fast-only (ignored otherwise)
#    tail_weight: 0.5


