# @package _global_
defaults:
  - /hydra: default
  - /envs@env_train: warmup
  - /rewards@env_train.reward: codemy_heuristic_delta
  - /envs@env_eval: empty
  - /rewards@env_eval.reward: codemy_heuristic_delta
  - /sb3_policies@policy: cnn1
  - /trains@_global_: imitation
  - _self_

log_level: info

run:
  name: cnn_imitation_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 1
  vec: dummy



