# @package _global_
defaults:
  - hydra: default
  - conf/envs@env_train: train_warmup
  - conf/rewards@env_train.reward: codemy_heuristic_delta
  - conf/envs@env_eval: eval_empty
  - conf/rewards@env_eval.reward: codemy_heuristic_delta
  - conf/sb3_policies@policy: cnn1
  - conf/trains@_global_: imitation
  - _self_

log_level: info

run:
  name: cnn_imitation_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 1
  vec: dummy
