# @package _global_
defaults:
  - hydra: default
  - env_bundles: macro_discrete_warmup
  - models: cnn1
  - trains: ppo_bc_eval
  - _self_

log_level: info

run:
  name: cnn_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 12
  vec: subproc
