# @package _global_
defaults:
  - hydra: default
  - envs@env_train: train_warmup
  - rewards@env_train.reward: heuristic_delta
  - envs@env_eval: eval_empty
  - rewards@env_eval.reward: heuristic_delta
  - sb3_policies@policy: cnn1
  - trains@_global_: imitation
  - _self_

log_level: info

run:
  name: cnn_imitation_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 1
  vec: dummy
