run:
  name: cnn_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 32
  vec: subproc


# point to sub-configs (paths are strings)
specs:
  env: configs/env_bundles/macro_discrete_warmup.yaml
  model: configs/models/cnn3.yaml
  train: configs/trains/ppo_bc_eval.yaml
