# @package _global_
defaults:
  - hydra: default
  - envs@env_train: macro_warmup
  - envs@env_eval: macro_empty
  - models@model: cnn1
  - trains@train: ppo_bc_eval
  - _self_

log_level: info

run:
  name: cnn_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 12
  vec: subproc
