# @package _global_
defaults:
  - hydra: default
  - envs@env_train: train_warmup
  - rewards@env_train.reward: heuristic_delta
  - envs@env_eval: eval_empty
  - rewards@env_eval.reward: heuristic_delta
  - sb3_policies@policy: vit
  - trains@_global_: ppo_bc_eval
  - _self_

log_level: info

run:
  name: vit_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 12
  vec: subproc
