# @package _global_
defaults:
  - hydra: default
  - envs@env_train: macro_warmup
  - envs@env_eval: macro_empty
  - models@model: vit_plus_mlp
  - trains@train: ppo_bc_eval
  - _self_

log_level: info

run:
  name: vit_run
  seed: 0
  out_root: experiments
  tensorboard: true
  device: cuda
  n_envs: 32
  vec: subproc
