[package]
name = "tetris_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tetris_cli"
path = "src/main.rs"

[dependencies]
tetris_engine = { path = "../engine" }
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
